### ISSUE TITLE
インデントを揃えよう

### ISSUE THREAD

**Issue by ryoNagata001** [sskrtt/my-vue-practice#1]
https://github.com/sskrtt/my-vue-practice/blob/0766d4a6d9e0a97b55a4c8f9430cc450305359f6/src/components/HelloWorld.vue#L1-L22

インデントずれていると、
文書の構造がわかりにくくて、バグを発見しずらいから、インデントは揃えよう。
ちなみに俺はVSCodeにpluginを入れて、保存と同時にインデントが自動的に揃えられるようにしてる。

どっかでVSCodeのpluginをdigってみるといいかも

**Comment by sskrtt** [comment]
ありがとう。意識します。
